### PR TITLE
Feature-branch 

### PR DESCRIPTION
**Pull request by dasileker**
### **CR for contact form**

_**In this repo:**_

- cloned the initial repo.
- add form contact.
-  check linters.

### CODE REVIEW

**Review by ccobasi — CHANGES_REQUESTED** [review]
Hi @dasileker

**Review by ccobasi — CHANGES_REQUESTED** [review]
Hi @[dasileker ](https://github.com/dasileker)

Awesome job so far!! 

You've done really well so far. Your implementation followed the best practices. Overall, it's a pleasure to review your code, you passed almost all the checklist for this project +1 just a few issues left to work on............ 

### Status: Required Changes! 

- [x] Let's make your repo looks professional by applying one of the 5 professional repo basic rules, kindly update your README file.
Checkout out the below link for help, feel free to follow this template from pathwright recycle 

Kindly re-submit for review after making all those changes slightly_smiling_face Thumps -up await you.....
Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Review by AshakaE — APPROVED** [review]
Hi @dasileker , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ccobasi — COMMENTED** [review]
Hi [@dasileker](https://github.com/dasileker),

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

##Highlights  

- You have added a contact form at the end of the form

##Required Changes 

- [ ] When I submit the contact form to Formspree an error of form not found appears. Why not create an account, then create a new form, form spree will give you an integration code that you will use in your project. This way, when a user submits a request, they will get a message that the form was submitted successfully and you will receive the request in your email.
- [ ] I think it would be better to keep our design as close as possible to the original template. For example, the submit button should be orange in color. You can get the exact color from the [Figma template.](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)

##Kindly Request for another review when done

##Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better_

Cheers and Happy  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
